services:
  classificador-app:
    build: .
    container_name: classificador_projetos
    ports:
      - "8025:8025"
    environment:
      - TRANSFORMERS_CACHE=/tmp/transformers_cache
    restart: unless-stopped
